import { Platform, StyleSheet } from "react-native";
import { palette } from "../model";

export const appStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.chrome },
  appShell: { flex: 1, backgroundColor: palette.chrome },
  toolbar: { height: 58, flexDirection: "row", alignItems: "center", backgroundColor: palette.chrome, paddingHorizontal: 12, zIndex: 20 },
  trafficLights: { width: 62, flexDirection: "row", alignItems: "center", gap: 8, paddingLeft: 4 },
  trafficLight: { width: 12, height: 12, borderRadius: 6, borderWidth: StyleSheet.hairlineWidth, borderColor: "rgba(0,0,0,.22)", overflow: "hidden" },
  trafficLightShine: { position: "absolute", top: 1, left: 2, width: 6, height: 3.5, borderRadius: 2, backgroundColor: "rgba(255,255,255,.5)" },
  toolbarLeading: { flex: 1, flexDirection: "row", alignItems: "center", gap: 5 },
  toolbarCenter: { flexDirection: "row", alignItems: "center", gap: 9 },
  toolbarTrailing: { flex: 1, flexDirection: "row", justifyContent: "flex-end", gap: 6 },
  toolbarButton: { minWidth: 52, height: 50, paddingHorizontal: 7, alignItems: "center", justifyContent: "center", borderRadius: 12, gap: 1 },
  toolbarButtonActive: { backgroundColor: "rgba(0,0,0,.07)" },
  toolbarLabel: { fontSize: 9.5, color: palette.heading },
  pressed: { opacity: .65 },
  disabled: { opacity: .35 },
  viewMenu: { position: "absolute", top: 56, left: -68, width: 250, padding: 14, backgroundColor: "#fbfafc", borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: "#bcb9bf", shadowColor: "#000", shadowOffset: { width: 0, height: 10 }, shadowOpacity: .2, shadowRadius: 24, elevation: 12, zIndex: 100 },
  viewMenuTitle: { fontSize: 13, fontWeight: "700", textAlign: "center", marginBottom: 10 },
  viewMenuRow: { minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line },
  viewMenuAction: { minHeight: 38, flexDirection: "row", alignItems: "center", gap: 7, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line },
  viewMenuText: { fontSize: 12 },
  viewMenuFoot: { paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line, fontSize: 10, color: palette.muted },
  menuDismissLayer: { position: "absolute", top: 90, left: 0, right: 0, bottom: 0, zIndex: 10 },
  mobileHeader: { minHeight: 66, paddingHorizontal: 16, paddingVertical: 9, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line, backgroundColor: "#f7f5f8" },
  mobileEyebrow: { fontSize: 8, letterSpacing: 1.2, fontWeight: "700", color: palette.purpleDark },
  mobileTitle: { maxWidth: 220, fontSize: 23, fontWeight: "700", letterSpacing: -.4, color: palette.text },
  mobileHeaderActions: { flexDirection: "row", gap: 8 },
  mobileCircleButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: palette.purpleSoft, alignItems: "center", justifyContent: "center" },
  mobileAddButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: palette.purple, alignItems: "center", justifyContent: "center" },
  searchBar: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 9, paddingHorizontal: 14, paddingVertical: 6, backgroundColor: palette.chrome },
  searchInput: { flex: 1, height: 30, paddingHorizontal: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: palette.line, borderRadius: 15, backgroundColor: palette.surface, fontSize: 13, color: palette.text },
  searchDone: { color: palette.purpleDark, fontSize: 12, fontWeight: "600" },
  searchCount: { fontSize: 11, fontWeight: "700", color: "#8b888f", minWidth: 18, textAlign: "right" },
  workspace: { flex: 1, minHeight: 0, flexDirection: "row" },
  workspaceDesktop: { paddingHorizontal: 8, paddingBottom: 8, paddingTop: 2, backgroundColor: palette.chrome },
  desktopPane: { borderRadius: 12, overflow: "hidden" },
  railPane: { width: 82, marginRight: 8 },
  outlinePane: { flex: 1, minWidth: 320 },
  perspectiveRail: { flex: 1, width: 82, paddingHorizontal: 7, paddingVertical: 8, gap: 2, backgroundColor: palette.rail },
  perspectiveRailList: { flex: 1 },
  perspectiveRailScroll: { gap: 2, paddingBottom: 4 },
  perspectiveItem: { height: 59, alignItems: "center", justifyContent: "center", gap: 2, borderRadius: 12 },
  perspectiveItemSelected: { backgroundColor: "#e9e0f0" },
  perspectiveLabel: { maxWidth: 68, fontSize: 9.5, color: "#58555c" },
  perspectiveLabelSelected: { color: palette.purpleDark, fontWeight: "600" },
  perspectiveMore: { marginTop: "auto" },
  customRailDivider: { height: StyleSheet.hairlineWidth, marginHorizontal: 9, marginVertical: 5, backgroundColor: palette.line },
  railSettingsButton: { height: 36, alignItems: "center", justifyContent: "center", borderRadius: 12 },
  badge: { position: "absolute", right: -11, top: -4, minWidth: 15, height: 15, borderRadius: 8, paddingHorizontal: 3, alignItems: "center", justifyContent: "center", backgroundColor: "#8d8a91" },
  badgeSelected: { backgroundColor: palette.purpleDark },
  badgeText: { color: "#fff", fontSize: 8, fontWeight: "700" },
  sidebar: { flex: 1, backgroundColor: palette.sidebar },
  sidebarHeader: { height: 69, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  sidebarTitle: { fontSize: 19, fontWeight: "700", letterSpacing: -.25 },
  sidebarScroll: { paddingHorizontal: 8, paddingBottom: 50 },
  sidebarRow: { minHeight: 35, paddingHorizontal: 8, flexDirection: "row", alignItems: "center", gap: 7, borderRadius: 10 },
  sidebarRowSelected: { backgroundColor: "#d9d8dc" },
  sidebarRowHover: { backgroundColor: "rgba(0,0,0,.05)" },
  sidebarRowText: { flex: 1, fontSize: 12.5, fontWeight: "500", color: palette.text },
  sidebarCount: { fontSize: 10, color: palette.muted },
  sidebarHoldText: { color: "#8a6a1a" },
  sidebarStatusTag: { fontSize: 9, fontWeight: "700", color: "#8a9098" },
  sidebarSectionLabel: { marginTop: 16, marginBottom: 5, marginLeft: 8, fontSize: 8.5, letterSpacing: .7, fontWeight: "700", color: "#817e85" },
  projectDot: { width: 14, height: 14, borderWidth: 2, borderRadius: 7, backgroundColor: palette.sidebar },
  projectDotHold: { backgroundColor: "#c9a227" },
  projectDotDropped: { backgroundColor: "#9aa0a6" },
  projectDotStalled: { backgroundColor: "#d94b4b" },
  sidebarFooter: { position: "absolute", left: 0, right: 0, bottom: 0, height: 39, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 5, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line, backgroundColor: palette.sidebar },
  sidebarFooterText: { fontSize: 11, color: "#625f66" },
  sidebarEmpty: { paddingHorizontal: 24, paddingTop: 30, alignItems: "center", gap: 8 },
  sidebarEmptyText: { fontSize: 11, lineHeight: 16, textAlign: "center", color: "#8b888f" },
  forecastPast: { height: 35, paddingHorizontal: 7, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderRadius: 10 },
  forecastPastCount: { fontSize: 10, color: palette.danger, fontWeight: "700" },
  forecastDays: { paddingTop: 10, flexDirection: "row", justifyContent: "space-between", gap: 2 },
  forecastDay: { flex: 1, minWidth: 0, height: 52, alignItems: "center", justifyContent: "center", borderRadius: 12, gap: 1 },
  forecastDaySelected: { backgroundColor: palette.purple },
  forecastDayText: { fontSize: 9, lineHeight: 14, textAlign: "center", color: palette.muted, fontWeight: "600" },
  forecastDayWeek: { fontSize: 8, letterSpacing: 0.3, fontWeight: "700", color: palette.muted },
  forecastDayNum: { fontSize: 12, fontWeight: "700", color: "#3a373d" },
  forecastDayCount: { fontSize: 8, color: palette.purpleDark, fontWeight: "700" },
  forecastDayCountSelected: { color: "#fff" },
  forecastDayTextSelected: { color: "#fff" },
  forecastDayNumWrap: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  forecastDayToday: { borderWidth: 1.5, borderColor: palette.purple },
  forecastDayNumToday: { color: palette.purpleDark },
  forecastUpcoming: { height: 35, marginTop: 8, paddingHorizontal: 7, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderRadius: 10 },
  outline: { flex: 1, minWidth: 320, backgroundColor: palette.canvas },
  outlineHeader: { height: 69, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line },
  outlineHeaderCopy: { flex: 1 },
  outlineTitle: { fontSize: 24, lineHeight: 29, fontWeight: "700", letterSpacing: -.55, color: palette.text },
  outlineSubtitle: { fontSize: 10, color: palette.muted },
  iconButton: { width: 32, height: 32, alignItems: "center", justifyContent: "center", borderRadius: 10 },
  outlineBody: { flex: 1, position: "relative", overflow: "hidden" },
  outlineScroll: { flex: 1 },
  outlineContent: { paddingBottom: 48, paddingTop: 4 },
  outlineColumnsHeader: { minHeight: 22, marginHorizontal: 8, paddingLeft: 68, paddingRight: 10, flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 8 },
  outlineColumnHeader: { fontSize: 9, fontWeight: "700", letterSpacing: 0.4, color: palette.muted, textTransform: "uppercase" },
  outlineColumnProject: { width: 128 },
  outlineColumnTags: { width: 108 },
  outlineColumnDuration: { width: 64, textAlign: "right" },
  outlineColumnDefer: { width: 92 },
  outlineColumnDue: { width: 92 },
  outlineColumnCell: { fontSize: 9.5, color: palette.muted },
  outlineColumnCellStrong: { fontSize: 9.5, color: palette.text, fontWeight: "500" },
  projectGroup: { borderBottomWidth: 7, borderBottomColor: palette.groupRule },
  projectHeading: { minHeight: 63, marginHorizontal: 8, marginTop: 4, paddingHorizontal: 8, paddingVertical: 10, flexDirection: "row", alignItems: "flex-start", gap: 7, borderRadius: 12 },
  projectHeadingSelected: { backgroundColor: palette.purpleSelection },
  projectHeadingMain: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "flex-start", gap: 7 },
  projectHeadingRing: { width: 18, height: 18, marginTop: 1, borderWidth: 3, borderRadius: 9, backgroundColor: palette.surface },
  projectHeadingCopy: { flex: 1 },
  projectHeadingTitle: { fontSize: 13.5, lineHeight: 19, fontWeight: "700", color: palette.heading },
  projectHeadingNote: { fontSize: 10, lineHeight: 15, color: palette.muted },
  projectHeadingCount: { fontSize: 10, color: palette.muted },
  tagHeading: { minHeight: 54, marginHorizontal: 8, marginTop: 4, paddingHorizontal: 8, flexDirection: "row", alignItems: "center", gap: 9, borderRadius: 12 },
  taskRow: { minHeight: 52, marginHorizontal: 8, marginVertical: 1, paddingHorizontal: 10, paddingVertical: 7, flexDirection: "row", alignItems: "flex-start", gap: 9, borderRadius: 12, overflow: "visible", position: "relative" },
  taskRowCompact: { minHeight: 42, paddingVertical: 4 },
  taskRowSelected: { backgroundColor: palette.purpleSelection },
  taskRowHover: { backgroundColor: palette.rowHover },
  taskRowPressed: { opacity: .72 },
  statusRing: { marginTop: 1, borderWidth: 1.8, alignItems: "center", justifyContent: "center", backgroundColor: "transparent", overflow: "visible" },
  statusFlag: { position: "absolute", right: -6, bottom: -7 },
  collapseButton: { width: 22, height: 22, alignItems: "center", justifyContent: "center" },
  taskBody: { flex: 1, minWidth: 0 },
  taskTitleLine: { minHeight: 19, flexDirection: "row", alignItems: "center", gap: 4 },
  taskTitle: { flexShrink: 1, flex: 1, fontSize: 13, lineHeight: 18, color: palette.text },
  taskTitleInput: { minHeight: 20, padding: 0, margin: 0 },
  taskTitleSmall: { fontSize: 12, lineHeight: 17 },
  taskTitleLarge: { fontSize: 15, lineHeight: 20 },
  taskTitleResolved: { color: "#969299" },
  taskTitleCompleted: { textDecorationLine: "line-through" },
  outlineNote: { marginTop: 2, marginBottom: 2, fontSize: 11, lineHeight: 15, color: "#86828a" },
  taskMeta: { minHeight: 17, flexDirection: "row", alignItems: "center", gap: 5, overflow: "hidden" },
  taskMetaText: { maxWidth: 165, fontSize: 9.5, color: "#8b878f" },
  tagChip: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 10, backgroundColor: "rgba(110,108,115,.11)" },
  tagChipText: { fontSize: 8.5, color: "#77737b" },
  taskTail: { minHeight: 38, flexDirection: "row", alignItems: "center", gap: 7, paddingLeft: 5 },
  dueText: { fontSize: 9.5, color: "#77737b" },
  dueToday: { color: palette.danger, fontWeight: "600" },
  dueOverdue: { color: palette.overdue, fontWeight: "700" },
  dueSoon: { color: palette.dueSoon, fontWeight: "600" },
  deferText: { fontSize: 9.5, color: "#9a969e", fontStyle: "italic" },
  rowInfoButton: { marginLeft: 2 },
  newActionBar: { position: "absolute", left: 0, right: 0, bottom: 0, height: 40, paddingHorizontal: 17, flexDirection: "row", alignItems: "center", gap: 5, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line, backgroundColor: palette.canvas },
  newActionText: { fontSize: 11, color: "#625f66" },
  emptyState: { paddingVertical: 85, alignItems: "center" },
  emptyCheck: { width: 48, height: 48, borderRadius: 24, borderWidth: 2, borderColor: "#b7b3ba", alignItems: "center", justifyContent: "center" },
  emptyTitle: { marginTop: 13, marginBottom: 4, fontSize: 17, fontWeight: "700", color: palette.heading },
  emptyText: { fontSize: 11, color: palette.muted },
  inlineNewAction: { minHeight: 34, paddingHorizontal: 18, paddingLeft: 48, flexDirection: "row", alignItems: "center", gap: 6 },
  inlineNewActionText: { fontSize: 12, fontWeight: "600", color: palette.purpleDark },
  estimateText: { fontSize: 10, color: "#8a9098", fontVariant: ["tabular-nums"] },
  paneHandle: { width: 8, backgroundColor: "transparent" },
  migrateState: { paddingVertical: 72, paddingHorizontal: 28, alignItems: "center" },
  migrateIcon: { width: 56, height: 56, marginBottom: 14, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: palette.purpleSoft },
  migrateTitle: { marginBottom: 8, fontSize: 18, fontWeight: "700", textAlign: "center", color: palette.text },
  migrateText: { maxWidth: 420, marginBottom: 16, fontSize: 11, lineHeight: 16, textAlign: "center", color: palette.muted },
  migrateButton: { minHeight: 34, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 10, backgroundColor: palette.purple },
  migrateButtonText: { fontSize: 12, fontWeight: "700", color: "#fff" },
  migrateHint: { marginTop: 12, fontSize: 10, color: "#8f8b93" },
  importLead: { fontSize: 11, lineHeight: 16, color: "#5f5b63" },
  reviewRow: { minHeight: 66, paddingHorizontal: 17, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line },
  reviewCopy: { flex: 1 },
  reviewButton: { height: 29, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: palette.purple, borderRadius: 10 },
  reviewButtonText: { color: "#fff", fontSize: 10, fontWeight: "600" },
  skipButton: { height: 29, paddingHorizontal: 10, alignItems: "center", justifyContent: "center", borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: "#ccc9cf", backgroundColor: "#fff" },
  skipButtonText: { fontSize: 10, fontWeight: "600", color: "#5f5c63" },
  reviewActionRow: { marginTop: 10, flexDirection: "row", gap: 8 },
  emptyInspector: { flex: 1, paddingHorizontal: 24, paddingTop: 64, alignItems: "center" },
  tagTokenRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 6 },
  tagToken: { minHeight: 24, paddingHorizontal: 8, flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 12, backgroundColor: palette.purpleSoft },
  tagTokenText: { fontSize: 10, fontWeight: "600", color: palette.purpleDark },
  inspector: { flex: 1, backgroundColor: palette.inspector },
  inspectorModal: { flex: 1, width: "100%", borderLeftWidth: 0 },
  inspectorTabs: { height: 43, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 4 },
  inspectorTabBar: { flex: 1, height: 28, padding: 2, flexDirection: "row", alignItems: "center", borderRadius: 9, backgroundColor: "#e4e2e6" },
  inspectorTabSelected: { flex: 1, height: 24, alignItems: "center", justifyContent: "center", borderRadius: 7, backgroundColor: "#fff", shadowColor: "#000", shadowOpacity: 0.08, shadowRadius: 2, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  inspectorTab: { flex: 1, height: 24, alignItems: "center", justifyContent: "center", borderRadius: 7 },
  inspectorTabText: { fontSize: 9.5, color: "#5f5c63" },
  inspectorTabTextSelected: { color: palette.text, fontWeight: "700" },
  inspectorNotePane: { flex: 1, padding: 12 },
  inspectorNoteEditor: { flex: 1, minHeight: 220, padding: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: "#cfccd2", borderRadius: 12, backgroundColor: "#fff", fontSize: 13, lineHeight: 18, color: palette.text },
  notePreview: { fontSize: 11, lineHeight: 16, color: "#4e4a51" },
  attachmentEmpty: { flex: 1, paddingHorizontal: 28, paddingTop: 48, alignItems: "center" },
  attachmentIcon: { width: 52, height: 52, marginBottom: 12, alignItems: "center", justifyContent: "center", borderRadius: 26, borderWidth: 1.5, borderColor: "#cfcdd2" },
  attachmentTitle: { marginBottom: 6, fontSize: 15, fontWeight: "700", color: "#67636a" },
  attachmentText: { fontSize: 11, lineHeight: 16, textAlign: "center", color: "#8f8b93" },
  datePresets: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginBottom: 6 },
  datePreset: { minHeight: 24, paddingHorizontal: 9, alignItems: "center", justifyContent: "center", borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: "#d0ced3", backgroundColor: "#fff" },
  datePresetSelected: { borderColor: palette.purple, backgroundColor: palette.purpleSoft },
  datePresetText: { fontSize: 9, color: "#5f5c63" },
  datePresetTextSelected: { color: palette.purpleDark, fontWeight: "700" },
  focusBar: { minHeight: 32, marginHorizontal: 8, marginTop: 4, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#ece3f4", borderRadius: 10 },
  focusBarText: { flex: 1, fontSize: 12, fontWeight: "600", color: "#4a2d66" },
  unfocusButton: { height: 24, paddingHorizontal: 10, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: palette.purple },
  unfocusButtonText: { fontSize: 10, fontWeight: "700", color: "#fff" },
  modalClose: { marginRight: "auto" },
  inspectorScroll: { flex: 1 },
  multiSelectBody: { flex: 1, paddingHorizontal: 22, paddingTop: 36, alignItems: "center" },
  multiSelectCount: { fontSize: 42, lineHeight: 46, fontWeight: "700", color: palette.purpleDark },
  multiSelectLabel: { marginTop: 2, fontSize: 13, fontWeight: "600", color: "#3a373d" },
  multiSelectHint: { marginTop: 10, marginBottom: 22, fontSize: 11, lineHeight: 16, textAlign: "center", color: palette.muted },
  multiSelectButton: { width: "100%", height: 34, marginBottom: 8, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: "#ccc9cf", backgroundColor: "#fff" },
  multiSelectButtonText: { fontSize: 12, fontWeight: "600", color: "#3a373d" },
  inspectorTitleRow: { minHeight: 82, padding: 13, flexDirection: "row", alignItems: "flex-start", gap: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line },
  inspectorTitleInput: { flex: 1, minHeight: 45, padding: 0, fontSize: 13, lineHeight: 18, color: palette.text, textAlignVertical: "top" },
  inspectorSection: { paddingHorizontal: 13, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line },
  inspectorSectionTitle: { marginBottom: 8, fontSize: 8.5, letterSpacing: .45, fontWeight: "700", color: "#77737b" },
  fieldLabel: { marginTop: 5, marginBottom: 3, fontSize: 9.5, color: "#706c74" },
  fieldInput: { minHeight: 28, paddingHorizontal: 8, paddingVertical: 4, borderWidth: StyleSheet.hairlineWidth, borderColor: "#cfccd2", borderRadius: 10, backgroundColor: "rgba(255,255,255,.74)", fontSize: 10.5, color: "#353238" },
  infoRow: { minHeight: 22, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  infoLabel: { fontSize: 10, color: "#706c74" },
  infoValue: { fontSize: 10, color: "#3a373d" },
  inspectorColor: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: "transparent" },
  inspectorColorSelected: { borderColor: "#fff", shadowColor: "#000", shadowOpacity: 0.25, shadowRadius: 3, elevation: 3 },
  noteInput: { minHeight: 96, paddingTop: 7 },
  choiceRow: { gap: 5, paddingBottom: 4 },
  choiceChip: { maxWidth: 170, height: 27, paddingHorizontal: 9, alignItems: "center", justifyContent: "center", borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: "#ccc9cf", backgroundColor: "rgba(255,255,255,.7)" },
  choiceChipSelected: { borderColor: palette.purple, backgroundColor: palette.purpleSoft },
  choiceText: { fontSize: 9.5, color: "#5c5960" },
  choiceTextSelected: { color: palette.purpleDark, fontWeight: "600" },
  savedRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, paddingBottom: 11 },
  savedText: { fontSize: 9, color: "#778079" },
  deleteButton: { height: 31, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, borderWidth: StyleSheet.hairlineWidth, borderColor: "#dfb5b5", borderRadius: 10, backgroundColor: "#fff9f9" },
  deleteButtonText: { color: palette.danger, fontSize: 10.5, fontWeight: "600" },
  modalBackdrop: { flex: 1, justifyContent: "center", alignItems: "center", padding: 18, backgroundColor: "rgba(29,25,32,.24)" },
  quickEntryCard: { width: "100%", maxWidth: 680, overflow: "hidden", borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, borderColor: "#aaa7ad", backgroundColor: "#fbfafc", shadowColor: "#000", shadowOffset: { width: 0, height: 20 }, shadowOpacity: .28, shadowRadius: 40, elevation: 16 },
  quickEntryHeader: { height: 42, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line, backgroundColor: "#f0eff1" },
  quickEntryHeaderText: { fontSize: 12, fontWeight: "700", color: "#37343a" },
  quickInputRow: { minHeight: 67, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: "#fff" },
  quickRing: { width: 19, height: 19, borderRadius: 10, borderWidth: 1.8, borderColor: "#8e8a92" },
  quickInput: { flex: 1, height: 43, fontSize: 16, color: palette.text },
  quickProjectRow: { paddingHorizontal: 46, paddingVertical: 9, gap: 6, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "#eceaed", backgroundColor: "#fff" },
  quickProjectChip: { maxWidth: 175, height: 29, paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: "#d2cfd5", backgroundColor: "#f5f4f6" },
  quickProjectChipSelected: { borderColor: palette.purple, backgroundColor: palette.purpleSoft },
  quickProjectText: { flexShrink: 1, fontSize: 9.5, color: "#5f5c63" },
  quickMeta: { paddingHorizontal: 16, paddingBottom: 12, gap: 4, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "#eceaed", backgroundColor: "#fff" },
  miniDot: { width: 7, height: 7, borderRadius: 4 },
  quickFooter: { minHeight: 50, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 8, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line },
  quickHint: { flex: 1, fontSize: 8.5, color: "#98949c" },
  cancelButton: { height: 29, minWidth: 68, alignItems: "center", justifyContent: "center", borderWidth: StyleSheet.hairlineWidth, borderColor: "#c9c6cc", borderRadius: 10, backgroundColor: "#fff" },
  cancelButtonText: { fontSize: 10.5, color: "#555159" },
  saveButton: { height: 29, minWidth: 68, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: palette.purple },
  saveButtonText: { fontSize: 10.5, color: "#fff", fontWeight: "700" },
  perspectiveModalBackdrop: { flex: 1, alignItems: "center", justifyContent: "center", padding: 16, backgroundColor: "rgba(29,25,32,.3)" },
  perspectiveEditor: { width: "100%", maxWidth: 720, maxHeight: "92%", overflow: "hidden", borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, borderColor: "#aaa7ad", backgroundColor: "#f5f3f6", shadowColor: "#000", shadowOffset: { width: 0, height: 20 }, shadowOpacity: .28, shadowRadius: 42, elevation: 18 },
  perspectiveEditorHeader: { height: 52, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line, backgroundColor: "#efedf0" },
  perspectiveEditorTitle: { fontSize: 14, fontWeight: "700", color: palette.text },
  editorCancelText: { minWidth: 52, fontSize: 12, color: palette.muted },
  editorSaveText: { minWidth: 52, textAlign: "right", fontSize: 12, fontWeight: "700", color: palette.purpleDark },
  perspectiveEditorScroll: { flexGrow: 0 },
  perspectiveEditorContent: { padding: 18, paddingBottom: 30 },
  perspectiveIdentity: { flexDirection: "row", alignItems: "center", gap: 13, marginBottom: 18 },
  perspectivePreviewIcon: { width: 54, height: 54, borderRadius: 16, alignItems: "center", justifyContent: "center" },
  perspectiveNameInput: { flex: 1, height: 44, paddingHorizontal: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: "#c8c5cb", borderRadius: 12, backgroundColor: "#fff", fontSize: 17, fontWeight: "600", color: palette.text },
  editorSectionTitle: { marginTop: 4, marginBottom: 7, fontSize: 8.5, letterSpacing: .8, fontWeight: "700", color: "#77737b" },
  iconChoiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 15 },
  iconChoice: { width: 39, height: 39, alignItems: "center", justifyContent: "center", borderWidth: StyleSheet.hairlineWidth, borderColor: "#cecad1", borderRadius: 12, backgroundColor: "#fff" },
  colorChoiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginBottom: 17 },
  colorChoice: { width: 29, height: 29, alignItems: "center", justifyContent: "center", borderRadius: 15, borderWidth: 2, borderColor: "transparent" },
  colorChoiceSelected: { borderColor: "#fff", shadowColor: "#000", shadowOpacity: .22, shadowRadius: 3, elevation: 3 },
  ruleCard: { padding: 14, marginBottom: 13, borderWidth: StyleSheet.hairlineWidth, borderColor: "#d3d0d5", borderRadius: 14, backgroundColor: "#fff" },
  ruleCardHeader: { flexDirection: "row", alignItems: "center", gap: 7, marginBottom: 8 },
  ruleCardTitle: { fontSize: 13, fontWeight: "700", color: palette.text },
  ruleLabel: { marginTop: 10, marginBottom: 5, fontSize: 10, fontWeight: "600", color: "#5f5b63" },
  ruleOptional: { fontWeight: "400", color: "#98949c" },
  ruleChoices: { flexDirection: "row", flexWrap: "wrap", gap: 5 },
  ruleChoice: { minHeight: 29, paddingHorizontal: 10, alignItems: "center", justifyContent: "center", borderWidth: StyleSheet.hairlineWidth, borderColor: "#cfccd2", borderRadius: 10, backgroundColor: "#f7f6f8" },
  ruleChoiceSelected: { borderColor: palette.purple, backgroundColor: palette.purpleSoft },
  ruleChoiceText: { fontSize: 9.5, color: "#67636b" },
  ruleChoiceTextSelected: { color: palette.purpleDark, fontWeight: "700" },
  projectRuleWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  projectRuleChip: { minHeight: 29, maxWidth: "100%", paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 5, borderWidth: StyleSheet.hairlineWidth, borderColor: "#cfccd2", borderRadius: 10, backgroundColor: "#f7f6f8" },
  projectRuleText: { flexShrink: 1, fontSize: 9.5, color: "#67636b" },
  editorInput: { minHeight: 34, paddingHorizontal: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: "#c9c6cc", borderRadius: 10, backgroundColor: "#fbfafc", fontSize: 11, color: palette.text },
  matchRow: { minHeight: 37, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  matchRowText: { fontSize: 10, color: "#67636b" },
  deletePerspectiveButton: { height: 38, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, borderWidth: StyleSheet.hairlineWidth, borderColor: "#dfb5b5", borderRadius: 10, backgroundColor: "#fff9f9" },
  deletePerspectiveText: { fontSize: 11, fontWeight: "600", color: palette.danger },
  settingsBackdrop: { flex: 1, alignItems: "center", justifyContent: "center", padding: 18, backgroundColor: "rgba(27,24,30,.34)" },
  settingsWindow: { width: "100%", maxWidth: 780, height: "82%", maxHeight: 610, minHeight: 480, overflow: "hidden", borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, borderColor: "#aaa7ad", backgroundColor: "#f7f6f8", shadowColor: "#000", shadowOffset: { width: 0, height: 24 }, shadowOpacity: .3, shadowRadius: 48, elevation: 20 },
  settingsWindowCompact: { height: "96%", maxHeight: "96%", minHeight: 0 },
  settingsTitlebar: { height: 49, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#c9c6cc", backgroundColor: "#eceaed" },
  settingsTrafficLights: { position: "absolute", left: 15, flexDirection: "row", gap: 8 },
  settingsTitle: { fontSize: 13, fontWeight: "700", color: "#37343a" },
  settingsDoneButton: { position: "absolute", right: 12, minWidth: 48, height: 28, alignItems: "center", justifyContent: "center", borderRadius: 10 },
  settingsDoneText: { fontSize: 11, fontWeight: "600", color: palette.purpleDark },
  settingsBody: { flex: 1, minHeight: 0, flexDirection: "row" },
  settingsBodyCompact: { flexDirection: "column" },
  settingsSidebar: { width: 178, padding: 12, gap: 3, backgroundColor: "#e8e6ea", borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: "#c9c6cc" },
  settingsSidebarCompact: { width: "100%", height: 58, paddingHorizontal: 8, paddingVertical: 8, flexDirection: "row", borderRightWidth: 0, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#c9c6cc" },
  settingsNavItem: { height: 39, paddingHorizontal: 8, flexDirection: "row", alignItems: "center", gap: 9, borderRadius: 10 },
  settingsNavItemCompact: { flex: 1, height: 40, justifyContent: "center", paddingHorizontal: 5, gap: 5 },
  settingsNavItemSelected: { backgroundColor: "#d8c9e5" },
  settingsNavIcon: { width: 27, height: 27, alignItems: "center", justifyContent: "center", borderRadius: 8, backgroundColor: "#d5d2d8" },
  settingsNavIconSelected: { backgroundColor: palette.purple },
  settingsNavText: { fontSize: 11.5, color: "#4c4850" },
  settingsNavTextSelected: { color: "#3d254f", fontWeight: "600" },
  settingsContent: { flex: 1, backgroundColor: "#f8f7f9" },
  settingsContentInner: { paddingHorizontal: 28, paddingTop: 25, paddingBottom: 35 },
  settingsContentInnerCompact: { paddingHorizontal: 14, paddingTop: 18, paddingBottom: 26 },
  settingsPageTitle: { fontSize: 21, lineHeight: 27, fontWeight: "700", letterSpacing: -.35, color: palette.text },
  settingsPageIntro: { marginTop: 4, marginBottom: 20, fontSize: 10.5, lineHeight: 16, color: palette.muted },
  settingsGroupLabel: { marginTop: 2, marginBottom: 6, marginLeft: 3, fontSize: 8, letterSpacing: .7, fontWeight: "700", color: "#817d85" },
  settingsGroup: { marginBottom: 18, overflow: "hidden", borderWidth: StyleSheet.hairlineWidth, borderColor: "#d2cfd5", borderRadius: 14, backgroundColor: "#fff" },
  settingsRow: { minHeight: 58, paddingHorizontal: 13, paddingVertical: 9, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#e3e1e5" },
  settingsStackedRow: { minHeight: 74, paddingHorizontal: 13, paddingVertical: 11, gap: 7, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#e3e1e5" },
  settingsRowCopy: { flex: 1, minWidth: 0 },
  settingsRowTitle: { fontSize: 11.5, fontWeight: "600", color: "#37343a" },
  settingsRowDetail: { marginTop: 2, fontSize: 9, lineHeight: 13, color: "#89858d" },
  settingsRowControl: { alignItems: "flex-end" },
  databaseCard: { minHeight: 76, marginBottom: 18, padding: 12, flexDirection: "row", alignItems: "center", gap: 11, borderWidth: StyleSheet.hairlineWidth, borderColor: "#d2cfd5", borderRadius: 14, backgroundColor: "#fff" },
  databaseIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: palette.purpleSoft },
  databaseCopy: { flex: 1 },
  databaseTitle: { fontSize: 12, fontWeight: "700", color: palette.text },
  databaseDetail: { marginTop: 3, fontSize: 9.5, color: palette.muted },
  databaseStatus: { flexDirection: "row", alignItems: "center", gap: 4 },
  databaseStatusDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#58a65c" },
  databaseStatusText: { fontSize: 9, color: "#667368" },
  settingsActionButton: { minHeight: 30, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 5, borderWidth: StyleSheet.hairlineWidth, borderColor: "#c9c6cc", borderRadius: 10, backgroundColor: "#f7f6f8" },
  settingsActionText: { fontSize: 10, fontWeight: "600", color: palette.purpleDark },
  resetSettingsButton: { minHeight: 34, alignSelf: "flex-start", paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 6, borderWidth: StyleSheet.hairlineWidth, borderColor: "#dfb5b5", borderRadius: 10, backgroundColor: "#fff9f9" },
  resetSettingsText: { fontSize: 10, fontWeight: "600", color: palette.danger },
  confirmBackdrop: { flex: 1, alignItems: "center", justifyContent: "center", padding: 18, backgroundColor: "rgba(27,24,30,.32)" },
  confirmDismissLayer: { ...StyleSheet.absoluteFill, zIndex: 0 },
  confirmCard: { width: "100%", maxWidth: 390, padding: 20, alignItems: "center", borderWidth: StyleSheet.hairlineWidth, borderColor: "#aaa7ad", borderRadius: 18, backgroundColor: "#fbfafc", shadowColor: "#000", shadowOffset: { width: 0, height: 16 }, shadowOpacity: .24, shadowRadius: 32, elevation: 18, zIndex: 1 },
  confirmIcon: { width: 45, height: 45, marginBottom: 11, alignItems: "center", justifyContent: "center", borderRadius: 23, backgroundColor: "#f7e4e4" },
  confirmTitle: { maxWidth: "100%", fontSize: 15, fontWeight: "700", color: palette.text },
  confirmText: { marginTop: 5, fontSize: 10, lineHeight: 15, textAlign: "center", color: palette.muted },
  confirmActions: { width: "100%", marginTop: 18, flexDirection: "row", justifyContent: "flex-end", gap: 8 },
  confirmDeleteButton: { height: 29, minWidth: 72, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: palette.danger },
  confirmDeleteText: { fontSize: 10.5, fontWeight: "700", color: "#fff" },
  importBackdrop: { flex: 1, alignItems: "center", justifyContent: "center", padding: 16, backgroundColor: "rgba(29,25,32,.34)" },
  importCard: { width: "100%", maxWidth: 620, maxHeight: "90%", overflow: "hidden", borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, borderColor: "#aaa7ad", backgroundColor: "#f8f7f9", shadowColor: "#000", shadowOffset: { width: 0, height: 20 }, shadowOpacity: .3, shadowRadius: 42, elevation: 18 },
  importHeader: { minHeight: 53, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line, backgroundColor: "#efedf0" },
  importHeaderTitle: { flexDirection: "row", alignItems: "center", gap: 8 },
  importTitle: { fontSize: 14, fontWeight: "700", color: palette.text },
  importContent: { padding: 18, gap: 12 },
  importSourceRow: { minHeight: 62, padding: 10, flexDirection: "row", alignItems: "center", gap: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: "#d0cdd3", borderRadius: 14, backgroundColor: "#fff" },
  importFileIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: palette.purpleSoft },
  importSourceCopy: { flex: 1, minWidth: 0 },
  importFileName: { fontSize: 12.5, fontWeight: "700", color: palette.text },
  importFormat: { marginTop: 2, fontSize: 9.5, color: palette.muted },
  importSectionTitle: { marginTop: 3, fontSize: 8.5, letterSpacing: .8, fontWeight: "700", color: "#77737b" },
  importStats: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  importStat: { flexGrow: 1, flexBasis: 72, minHeight: 62, padding: 8, alignItems: "center", justifyContent: "center", borderWidth: StyleSheet.hairlineWidth, borderColor: "#d6d3d8", borderRadius: 12, backgroundColor: "#fff" },
  importStatValue: { fontSize: 20, lineHeight: 23, fontWeight: "700", color: palette.purpleDark },
  importStatLabel: { marginTop: 2, fontSize: 8.5, color: palette.muted },
  importProjectList: { overflow: "hidden", borderWidth: StyleSheet.hairlineWidth, borderColor: "#d6d3d8", borderRadius: 12, backgroundColor: "#fff" },
  importProjectRow: { minHeight: 34, paddingHorizontal: 11, flexDirection: "row", alignItems: "center", gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#ebe9ec" },
  importProjectName: { flex: 1, fontSize: 10.5, color: "#4e4a51" },
  importProjectCount: { fontSize: 9, color: palette.muted },
  importMore: { padding: 10, fontSize: 9.5, textAlign: "center", color: palette.purpleDark },
  importWarning: { padding: 10, flexDirection: "row", alignItems: "flex-start", gap: 7, borderRadius: 12, backgroundColor: "#fff4dd" },
  importWarningText: { flex: 1, fontSize: 9.5, lineHeight: 14, color: "#75531f" },
  importHelp: { fontSize: 9.5, lineHeight: 14, color: palette.muted },
  replaceConfirm: { padding: 12, gap: 6, borderWidth: StyleSheet.hairlineWidth, borderColor: "#e3baba", borderRadius: 12, backgroundColor: "#fff7f7" },
  replaceConfirmTitle: { fontSize: 11.5, fontWeight: "700", color: palette.danger },
  replaceConfirmText: { fontSize: 9.5, lineHeight: 14, color: "#765b5b" },
  replaceConfirmActions: { marginTop: 5, flexDirection: "row", justifyContent: "flex-end", gap: 8 },
  replaceButton: { height: 29, paddingHorizontal: 12, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: palette.danger },
  replaceButtonText: { fontSize: 10, fontWeight: "700", color: "#fff" },
  importMessageContent: { paddingHorizontal: 28, paddingVertical: 34, alignItems: "center" },
  importMessageIcon: { width: 58, height: 58, marginBottom: 13, alignItems: "center", justifyContent: "center", borderRadius: 29 },
  importMessageIconSuccess: { backgroundColor: "#e2f0e3" },
  importMessageIconError: { backgroundColor: "#f8e4e4" },
  importMessageTitle: { marginBottom: 7, fontSize: 17, fontWeight: "700", color: palette.text },
  importMessageText: { maxWidth: 450, fontSize: 11, lineHeight: 17, textAlign: "center", color: palette.muted },
  exportInstructions: { width: "100%", marginTop: 18, padding: 13, gap: 5, borderWidth: StyleSheet.hairlineWidth, borderColor: "#d6d3d8", borderRadius: 12, backgroundColor: "#fff" },
  exportInstructionsTitle: { marginBottom: 2, fontSize: 10.5, fontWeight: "700", color: palette.text },
  exportInstruction: { fontSize: 9.5, lineHeight: 15, color: "#5f5b63" },
  importFooter: { minHeight: 56, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 8, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line, backgroundColor: "#f0eff1" },
  importReplaceButton: { height: 31, minWidth: 72, alignItems: "center", justifyContent: "center", borderWidth: StyleSheet.hairlineWidth, borderColor: "#dfb5b5", borderRadius: 10, backgroundColor: "#fff9f9" },
  importReplaceText: { fontSize: 10.5, color: palette.danger },
  importMergeButton: { height: 31, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, borderRadius: 10, backgroundColor: palette.purple },
  importMergeText: { fontSize: 10.5, fontWeight: "700", color: "#fff" },
  mobileNav: { minHeight: 62, paddingTop: 5, paddingBottom: Platform.OS === "ios" ? 4 : 6, flexDirection: "row", alignItems: "center", borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line, backgroundColor: "#f7f5f8" },
  mobileNavList: { flex: 1 },
  mobileNavScroll: { paddingHorizontal: 3 },
  mobileNavItem: { width: 64, alignItems: "center", justifyContent: "center", gap: 2, borderRadius: 12, paddingVertical: 4 },
  mobileNavItemSelected: { backgroundColor: palette.purpleSoft },
  mobileNavLabel: { maxWidth: 58, fontSize: 8, color: "#77747b" },
  mobileNavLabelSelected: { color: palette.purpleDark, fontWeight: "700" },
  calendarCard: { marginBottom: 8, padding: 8, borderWidth: StyleSheet.hairlineWidth, borderColor: "#d4d1d6", borderRadius: 12, backgroundColor: "#fff" },
  calendarHeader: { minHeight: 28, marginBottom: 6, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  calendarNav: { width: 26, height: 26, alignItems: "center", justifyContent: "center", borderRadius: 13 },
  calendarTitle: { fontSize: 12, fontWeight: "700", color: "#3a373d" },
  calendarWeekRow: { flexDirection: "row", marginBottom: 2 },
  calendarWeekday: { flex: 1, textAlign: "center", fontSize: 8, fontWeight: "700", color: "#8b888f" },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  calendarDay: { width: "14.285%", height: 28, alignItems: "center", justifyContent: "center", borderRadius: 14 },
  calendarDayMuted: { opacity: 0.45 },
  calendarDaySelected: { backgroundColor: palette.purple },
  calendarDayToday: { borderWidth: 1.5, borderColor: palette.purple },
  calendarDayText: { fontSize: 10, fontWeight: "600", color: "#3a373d" },
  calendarDayTextSelected: { color: "#fff" },
  calendarDayTextMuted: { color: "#8b888f" },
  calendarClear: { alignSelf: "flex-start", marginTop: 4, minHeight: 22, justifyContent: "center" },
  inlineDatePopover: { position: "absolute", right: 8, top: 34, width: 248, padding: 10, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: "#b7b4ba", backgroundColor: "#fbfafc", shadowColor: "#000", shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.2, shadowRadius: 16, elevation: 14, zIndex: 30 },
  sidebarRowDrop: { backgroundColor: "#e4d5ef", borderWidth: 1, borderColor: palette.purple },
  notificationHint: { marginTop: 8, fontSize: 10, lineHeight: 14, color: palette.muted },
  repeatEveryRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 },
  repeatEveryInput: { width: 48, minHeight: 28, paddingHorizontal: 8, borderWidth: StyleSheet.hairlineWidth, borderColor: "#cfccd2", borderRadius: 10, backgroundColor: "#fff", fontSize: 12, textAlign: "center", color: palette.text },
  toggleRow: { minHeight: 32, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  toggleTrack: { width: 34, height: 20, borderRadius: 10, backgroundColor: "#d5d2d7", justifyContent: "center", paddingHorizontal: 2 },
  toggleTrackOn: { backgroundColor: palette.purple },
  toggleThumb: { width: 16, height: 16, borderRadius: 8, backgroundColor: "#fff" },
  toggleThumbOn: { alignSelf: "flex-end" },
});
